name: Update Playlist

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate NBA playlist
        run: node generate-playlist.js nba

      - name: Generate NHL playlist
        run: node generate-playlist.js nhl

      - name: Generate MLB playlist
        run: node generate-playlist.js mlb

      - name: Generate NFL playlist
        run: node generate-playlist.js nfl

      - name: Generate MLS playlist
        run: node generate-playlist.js mls

      - name: Generate WNBA playlist
        run: node generate-playlist.js wnba

      - name: Generate UFC playlist
        run: node generate-playlist.js ufc

      - name: Generate BOXING playlist
        run: node generate-playlist.js boxing

      - name: Merge all playlists
        run: node merge.js

      - name: Commit and push merged playlist
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add merged.m3u
          git commit -m "🔄 Auto-update merged.m3u" || echo "No changes to commit"
          git push
